"""add goal.py model

Revision ID: 72107c219903
Revises: 28fe8bb46b24
Create Date: 2024-11-07 15:02:49.286144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72107c219903'
down_revision = '28fe8bb46b24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
